# Below you'll find an example configuration, showing you and explaining most
# (if not all) possible configurations you might need. If you are unsure about
# any of the explanations, be sure to also check out the documentation on the
# internal types that are configured through this TOML file:
#
#   https://docs.rs/dfw/*/dfw/types/index.html
#
# Each of the sections in this file matches to a struct under the same name,
# and every struct field contains some documentation that might help you out.

[backend_defaults]
# If you are already using nftables or are running a default nftables
# installation, chances are that you already have nftables table called
# "filter". For DFW to work correctly it is necessary to provide the existing
# tables and the names of their input and forward chains such that it can hook
# into them, ensuring that the traffic managed by DFW is correctly accepted or
# denied. (If you have multiple pre-existing tables, you can specify a list
# here, too.)
# The following is a sane default that should work for most setups.
custom_tables = { name = "filter", chains = ["input", "forward"] }

[backend_defaults.initialization]
# The backend-defaults table allows you to define any commands that you want
# executed against nftables when DFW applies the ruleset, in addition to the
# rules generated by DFW itself.
rules = [
    "add table inet custom",
    "flush table inet custom",
    # ...
]
