[package]
name = "server-os"
version = "0.1.0"
edition = "2021"
authors = ["TIA <tia@example.com>"]
description = "Security-hardened server OS dashboard launcher"
license = "MIT"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
sysinfo = "0.32"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }

[[bin]]
name = "os"
path = "src/main.rs"
