# This workflow triggers when a stable release is published on GitHub.
#
# The crates.io token used for publishing was created under the account of
# cyqsimon <28627918+cyqsimon@users.noreply.github.com> and was added to this
# repository's secrets by Aram Drevekenin <aram@poor.dev>.

name: publish-crate
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish-to-crates-io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run cargo publish
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
