sign-commit = true
sign-tag = true
tag-name = "{{version}}"

# Replace `docker pull pitkley/dfw:X.Y.Z`
[[pre-release-replacements]]
file = "README.md"
search = "pitkley/dfw:([0-9]+\\.?)+"
replace = "pitkley/dfw:{{version}}"
prerelease = false
[[pre-release-replacements]]
file = "docs/GETTING-STARTED-nftables.md"
search = "pitkley/dfw:([0-9]+\\.?)+"
replace = "pitkley/dfw:{{version}}"
prerelease = false
[[pre-release-replacements]]
file = "docs/GETTING-STARTED-iptables.md"
search = "pitkley/dfw:([0-9]+\\.?)+"
replace = "pitkley/dfw:{{version}}"
prerelease = false
[[pre-release-replacements]]
file = "examples/reverseproxy/README.md"
search = "pitkley/dfw:([0-9]+\\.?)+"
replace = "pitkley/dfw:{{version}}"
prerelease = false

# Replace `dfw X.Y.Z`
[[pre-release-replacements]]
file = "docs/GETTING-STARTED-nftables.md"
search = "dfw ([0-9]+\\.?)+"
replace = "dfw {{version}}"
prerelease = false
[[pre-release-replacements]]
file = "docs/GETTING-STARTED-iptables.md"
search = "dfw ([0-9]+\\.?)+"
replace = "dfw {{version}}"
prerelease = false

# Replace `dfw.rs/X.Y.Z/`
[[pre-release-replacements]]
file = "README.md"
search = "dfw\\.rs/([0-9]+\\.?)+/"
replace = "dfw.rs/{{version}}/"
prerelease = false
[[pre-release-replacements]]
file = "docs/GETTING-STARTED-nftables.md"
search = "dfw\\.rs/([0-9]+\\.?)+/"
replace = "dfw.rs/{{version}}/"
prerelease = false
[[pre-release-replacements]]
file = "docs/GETTING-STARTED-iptables.md"
search = "dfw\\.rs/([0-9]+\\.?)+/"
replace = "dfw.rs/{{version}}/"
prerelease = false

# Handle new section in CHANGELOG.md
# 1. Replace the fields in the unreleased header.
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## Unreleased"
replace = "## {{version}} ({{date}})"
exactly = 1
prerelease = false
# 2. Add a new unreleased header.
[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = "<!-- next-header -->\n\n## Unreleased"
exactly = 1
prerelease = false
