name: Checks

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
jobs:
    fmt:
        name: Format & Linter
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - name: clippy
          run: cargo clippy

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: swatinem/rust-cache@v2
        - name: build
          run: cargo build